[Service]
ExecStart=
# Skip username prompt on tty1; login still asks for password.
ExecStart=-/usr/bin/agetty --noreset --noclear --skip-login --login-options "deo" - ${TERM}

# sudo install -Dm644 ~/p3drovfx-dots/dots-extra/systemd/getty@tty1.service.d/username.conf \
#   /etc/systemd/system/getty@tty1.service.d/username.conf
# sudo systemctl daemon-reload
