-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.00", position = "0x0", scale = 1.00 })
hl.monitor({ output = "DP-1", mode = "3840x2160@239.99", position = "1920x0", scale = 2.00, bitdepth = 10 })
